### PR TITLE
fixing bigquery scaffold

### PR DESCRIPTION
**Pull request by beczkowb**
fixing pandas error

### CODE REVIEW

**Review by iwko — APPROVED** [review]

**Review by anjensan — CHANGES_REQUESTED** [review]
Could you add some comment, link to bug or somehow explain which issue this PR is resolving.
Maybe some stacktrace or explanation how changing version of 'pip' might solve 'pandas error'.

**Comment by beczkowb** [comment]
@anjensan the error:
```
[2020-10-28 14:48:01,435] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,434] {pod_launcher.py:125} INFO - b'/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/client.py:445: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.\n'
[2020-10-28 14:48:01,436] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,434] {pod_launcher.py:125} INFO - b'  "Cannot create BigQuery Storage client, the dependency "\n'
[2020-10-28 14:48:01,436] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,434] {pod_launcher.py:125} INFO - b'Traceback (most recent call last):\n'
[2020-10-28 14:48:01,438] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,434] {pod_launcher.py:125} INFO - b'  File "/usr/local/bin/bf", line 7, in <module>\n'
[2020-10-28 14:48:01,439] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,434] {pod_launcher.py:125} INFO - b'    cli(sys.argv[1:])\n'
[2020-10-28 14:48:01,439] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,434] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/cli.py", line 726, in cli\n'
[2020-10-28 14:48:01,439] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,434] {pod_launcher.py:125} INFO - b'    cli_run(root_package, parsed_args.runtime, parsed_args.job, parsed_args.workflow)\n'
[2020-10-28 14:48:01,440] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,434] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/cli.py", line 241, in cli_run\n'
[2020-10-28 14:48:01,440] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,435] {pod_launcher.py:125} INFO - b'    execute_job(project_package, workflow_id, job_id, runtime=runtime)\n'
[2020-10-28 14:48:01,440] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,435] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/cli.py", line 154, in execute_job\n'
[2020-10-28 14:48:01,441] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,435] {pod_launcher.py:125} INFO - b'    w.run_job(job_id, runtime)\n'
[2020-10-28 14:48:01,441] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,438] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/workflow.py", line 161, in run_job\n'
[2020-10-28 14:48:01,441] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,438] {pod_launcher.py:125} INFO - b'    self._execute_job(self.find_job(job_id), context)\n'
[2020-10-28 14:48:01,442] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,438] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/workflow.py", line 139, in _execute_job\n'
[2020-10-28 14:48:01,443] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,438] {pod_launcher.py:125} INFO - b'    job.execute(context)\n'
[2020-10-28 14:48:01,443] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,438] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/job.py", line 25, in execute\n'
[2020-10-28 14:48:01,444] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,438] {pod_launcher.py:125} INFO - b'    return self._run_component(self._build_dependencies(context.runtime_str))\n'
[2020-10-28 14:48:01,445] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,438] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/job.py", line 36, in _run_component\n'
[2020-10-28 14:48:01,446] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,440] {pod_launcher.py:125} INFO - b'    return self.component(**dependencies)\n'
[2020-10-28 14:48:01,447] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,440] {pod_launcher.py:125} INFO - b'  File "fakesource", line 2, in reworked_function\n'
[2020-10-28 14:48:01,447] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,440] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/interactive.py", line 233, in component_callable\n'
[2020-10-28 14:48:01,447] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,441] {pod_launcher.py:125} INFO - b'    component_return_value = standard_component(**operation_level_dataset_managers)\n'
[2020-10-28 14:48:01,448] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,441] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/interactive.py", line 145, in tmp_component\n'
[2020-10-28 14:48:01,449] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,442] {pod_launcher.py:125} INFO - b'    return getattr(_inline_component_dataset, method)(*args, **kwargs)\n'
[2020-10-28 14:48:01,449] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,443] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/interactive.py", line 274, in write_truncate\n'
[2020-10-28 14:48:01,450] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,443] {pod_launcher.py:125} INFO - b'    custom_run_datetime=custom_run_datetime)\n'
[2020-10-28 14:48:01,452] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,443] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/interactive.py", line 370, in _run_operation\n'
[2020-10-28 14:48:01,453] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,444] {pod_launcher.py:125} INFO - b'    return method(*args, sql=sql, **kwargs)\n'
[2020-10-28 14:48:01,453] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,445] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/dataset_manager.py", line 128, in write_truncate\n'
[2020-10-28 14:48:01,453] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,445] {pod_launcher.py:125} INFO - b'    custom_run_datetime)\n'
[2020-10-28 14:48:01,454] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,446] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/dataset_manager.py", line 195, in _write\n'
[2020-10-28 14:48:01,454] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,447] {pod_launcher.py:125} INFO - b'    return write_callable(table_id, sql, custom_run_datetime)\n'
[2020-10-28 14:48:01,454] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,447] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/dataset_manager.py", line 57, in write_truncate\n'
[2020-10-28 14:48:01,455] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,447] {pod_launcher.py:125} INFO - b'    return self.write(self.dataset_manager.write_truncate, table_name, sql, custom_run_datetime)\n'
[2020-10-28 14:48:01,455] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,448] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/dataset_manager.py", line 21, in decorated\n'
[2020-10-28 14:48:01,455] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,449] {pod_launcher.py:125} INFO - b'    return method(*args, **kwargs)\n'
[2020-10-28 14:48:01,456] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,449] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/dataset_manager.py", line 69, in write\n'
[2020-10-28 14:48:01,456] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,449] {pod_launcher.py:125} INFO - b'    return write_callable(table_id, sql.format(**self.template_variables(custom_run_datetime)))\n'
[2020-10-28 14:48:01,456] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,449] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/dataset_manager.py", line 236, in write_truncate\n'
[2020-10-28 14:48:01,457] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,453] {pod_launcher.py:125} INFO - b'    self.table_exists_or_error(table_id)\n'
[2020-10-28 14:48:01,458] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,453] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/dataset_manager.py", line 245, in table_exists_or_error\n'
[2020-10-28 14:48:01,458] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,453] {pod_launcher.py:125} INFO - b'    if not self.table_exists(table_name):\n'
[2020-10-28 14:48:01,459] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,453] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/bigflow/bigquery/dataset_manager.py", line 287, in table_exists\n'
[2020-10-28 14:48:01,460] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,453] {pod_launcher.py:125} INFO - b'    table_name=table_name)) \\\n'
[2020-10-28 14:48:01,460] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,453] {pod_launcher.py:125} INFO - b'  File "/usr/local/lib/python3.7/site-packages/google/cloud/bigquery/table.py", line 1757, in to_dataframe\n'
[2020-10-28 14:48:01,460] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,454] {pod_launcher.py:125} INFO - b'    df = record_batch.to_pandas(date_as_object=date_as_object, **extra_kwargs)\n'
[2020-10-28 14:48:01,460] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,454] {pod_launcher.py:125} INFO - b'  File "pyarrow/array.pxi", line 503, in pyarrow.lib._PandasConvertible.to_pandas\n'
[2020-10-28 14:48:01,461] {base_task_runner.py:113} INFO - Job 25109: Subtask select-polish-ports [2020-10-28 14:48:01,454] {pod_launcher.py:125} INFO - b"TypeError: to_pandas() got an unexpected keyword argument 'timestamp_as_object'\n"
```

**Comment by beczkowb** [comment]
@anjensan I have removed the duplicated beam installation which caused installing BQ client == 1.28.0 instead of 1.26.0. Looks like it solves the problem. The 2 lines in docker also did, but I have no idea why. pip forced reinstall on its own wasn't enough.

**Review by anjensan — APPROVED** [review]

**Comment by anjensan** [comment]
probably such type of issues (version mismatch) might be partially solved with #98

**Pull request merged**
